import type { Metadata } from "next";
import AdminLayout from "./components/AdminLayout";

export const metadata: Metadata = {
    title: "Web Auditor",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
       <AdminLayout>
           {children}
       </AdminLayout>
    );
}
